<?php
declare(strict_types=1);
namespace App\Http\Controllers;
use App\Core\Auth;use App\Support\AuditLogger;use App\Support\PersianDate;use App\Support\PersianText;use PDO;
final class RestaurantController{
 public static function page(PDO $db):array{
  self::ensureCart();self::restoreDraft($db);$orderType=self::orderType($db);$phone=trim((string)($_GET['phone']??$_SESSION['order_customer_phone']??''));$customer=$phone!==''?self::customerSearch($db,$phone):null;if($customer)$_SESSION['order_customer_phone']=$customer['phone'];
  [$items,$subtotal]=self::cart($db);$discountPercent=self::discountPercent();$discountAmount=self::discountAmount($subtotal,$discountPercent);$total=max(0,$subtotal-$discountAmount);
  $products=$db->query("SELECT p.*,c.name category_name,c.color category_color,c.icon category_icon FROM products p LEFT JOIN product_categories c ON c.name=p.product_type AND c.status='active' WHERE p.status='active' AND NOT EXISTS (SELECT 1 FROM inventory_product_rules r INNER JOIN inventory_items i ON i.id=r.inventory_item_id WHERE r.product_id=p.id AND i.status='active' AND i.track_stock=1 AND i.current_quantity<r.quantity_per_order) ORDER BY c.sort_order,c.name,p.name LIMIT 500")->fetchAll();$productTypes=$db->query("SELECT name,color,icon FROM product_categories WHERE status='active' ORDER BY sort_order,name")->fetchAll();$message=null;$error=null;
  try{if($_SERVER['REQUEST_METHOD']==='POST'){$action=(string)($_POST['action']??'');switch($action){
   case'add_customer_order':self::addCustomerFromOrder($db);$message='مشتری با موفقیت ثبت و انتخاب شد.';break;
   case'remove_customer_order':unset($_SESSION['order_customer_phone']);$customer=null;$phone='';$message='مشتری از سفارش حذف شد؛ اقلام سفارش حفظ شدند.';break;
   case'add_item':if(!$customer)throw new \RuntimeException('ابتدا مشتری را انتخاب کنید.');self::setSelectedProductType();self::addItem($db);break;
   case'remove_item':self::setSelectedProductType();self::decrementItem();break;
   case'clear_cart':self::setSelectedProductType();self::clearCart();self::setDiscount('0');self::forgetActiveDraft();$message='فاکتور فعلی خالی شد.';break;
   case'new_order':self::forgetActiveDraft();$customer=null;$phone='';$orderType=self::orderType($db);$message='فاکتور جدید آماده شد.';break;
   case'load_draft':$draftId=(int)($_POST['draft_id']??0);if($draftId<1)throw new \RuntimeException('فاکتور در دست اقدام نامعتبر است.');$draft=self::findDraft($db,$draftId);if(!$draft)throw new \RuntimeException('فاکتور در دست اقدام پیدا نشد.');self::loadDraft($db,$draft);$orderType=$draft['order_type'];$message='فاکتور در دست اقدام بارگذاری شد.';break;
   case'delete_draft':$draftId=(int)($_POST['draft_id']??0);self::deleteDraft($db,$draftId);$message='فاکتور در دست اقدام حذف شد.';break;
   case'set_order_type':$orderType=self::setOrderType($db);self::applyDefaultProducts($db,$orderType);$message='نوع سفارش تغییر کرد و اقلام قبلی حفظ شدند.';break;
   case'apply_discount':self::setDiscount((string)($_POST['discount_percent']??'0'));$message='تخفیف اعمال شد.';break;
   case'save_draft':self::setDiscount((string)($_POST['discount_percent']??'0'));$message='فاکتور در دست اقدام ذخیره شد.';break;
   case'finalize':self::setDiscount((string)($_POST['discount_percent']??'0'));$customerPhone=trim((string)($_POST['customer_phone']??$_SESSION['order_customer_phone']??''));$customer=self::customerSearch($db,$customerPhone);$result=self::finalize($db,$customer?:[]);header('Location: /?page=print&invoice='.rawurlencode($result['invoice_no']));exit;
  }$items=$items??[];$subtotal=$subtotal??0;$phone=trim((string)($_SESSION['order_customer_phone']??$phone));$customer=$phone!==''?self::customerSearch($db,$phone):null;if(in_array($action,['add_customer_order','add_item','remove_item','clear_cart','new_order','load_draft','set_order_type','apply_discount','save_draft'],true)){self::syncDraft($db,$customer);[$items,$subtotal]=self::cart($db);}$discountPercent=self::discountPercent();$discountAmount=self::discountAmount($subtotal,$discountPercent);$total=max(0,$subtotal-$discountAmount);}}catch(\Throwable $e){$error=self::friendly($e);}
  [$items,$subtotal]=self::cart($db);$discountPercent=self::discountPercent();$discountAmount=self::discountAmount($subtotal,$discountPercent);$total=max(0,$subtotal-$discountAmount);$selectedType=(string)($_SESSION['order_product_type_filter']??'all');$pendingDrafts=self::pendingDrafts($db);return compact('products','productTypes','items','subtotal','discountPercent','discountAmount','total','customer','phone','orderType','selectedType','pendingDrafts','message','error');
 }
 public static function customerSearch(PDO $db,string $query):?array{$query=PersianText::normalize($query);if($query==='')return null;$phone=self::normalizeDigits($query);$s=$db->prepare('SELECT * FROM customers WHERE phone=? OR name LIKE ? OR first_name LIKE ? OR last_name LIKE ? ORDER BY (phone=?) DESC,id DESC LIMIT 1');$like='%'.$query.'%';$s->execute([$phone,$like,$like,$like,$phone]);return$s->fetch()?:null;}
 public static function addCustomer(PDO $db):void{$phone=self::normalizeDigits($_POST['phone']??'');$first=PersianText::normalize($_POST['first_name']??'');$last=PersianText::normalize($_POST['last_name']??'');if($first===''||$last===''||$phone==='')throw new \RuntimeException('نام، نام خانوادگی و شماره تلفن الزامی است.');$s=$db->prepare('INSERT INTO customers(subscription_code,first_name,last_name,name,phone,mobile,membership_date,address,birth_date,created_at) VALUES(?,?,?,?,?,?,?,?,?,NOW())');$s->execute([PersianText::normalize($_POST['subscription_code']??'')?:null,$first,$last,trim($first.' '.$last),$phone,self::normalizeDigits($_POST['mobile']??'')?:null,PersianDate::toGregorian($_POST['membership_date']??''),PersianText::normalize($_POST['address']??'')?:null,PersianDate::toGregorian($_POST['birth_date']??'')]);}
 public static function addCustomerFromOrder(PDO $db):void{self::addCustomer($db);$_SESSION['order_customer_phone']=self::normalizeDigits($_POST['phone']??'');}
 public static function addProduct(PDO $db):void{$code=trim((string)($_POST['product_code']??''));$name=PersianText::normalize($_POST['name']??'');if($code===''||$name==='')throw new \RuntimeException('کد کالا و نام کالا الزامی است.');$type=PersianText::normalize($_POST['product_type']??'');$s=$db->prepare('INSERT INTO products(product_code,name,price,unit,product_type,allow_dine_in,allow_takeaway,status,created_at) VALUES(?,?,?,?,?,?,?, ?,NOW())');$s->execute([$code,$name,(float)($_POST['price']??0),PersianText::normalize($_POST['unit']??'')?:null,$type?:null,(int)!empty($_POST['allow_dine_in']),(int)!empty($_POST['allow_takeaway']),($_POST['status']??'active')==='active'?'active':'inactive']);}
 public static function updateCustomer(PDO $db):void{$id=(int)($_POST['id']??0);$phone=self::normalizeDigits($_POST['phone']??'');$first=PersianText::normalize($_POST['first_name']??'');$last=PersianText::normalize($_POST['last_name']??'');if($id<1||$first===''||$last===''||$phone==='')throw new \RuntimeException('نام، نام خانوادگی و شماره تلفن الزامی است.');$s=$db->prepare('UPDATE customers SET subscription_code=?,first_name=?,last_name=?,name=?,phone=?,mobile=?,membership_date=?,address=?,birth_date=?,updated_at=NOW() WHERE id=?');$s->execute([PersianText::normalize($_POST['subscription_code']??'')?:null,$first,$last,trim($first.' '.$last),$phone,self::normalizeDigits($_POST['mobile']??'')?:null,PersianDate::toGregorian($_POST['membership_date']??''),PersianText::normalize($_POST['address']??'')?:null,PersianDate::toGregorian($_POST['birth_date']??''),$id]);}
 public static function deleteCustomer(PDO $db):void{$id=(int)($_POST['id']??0);if($id<1)throw new \RuntimeException('مشتری نامعتبر است.');$db->prepare('DELETE FROM customers WHERE id=?')->execute([$id]);}
 public static function updateProduct(PDO $db):void{$id=(int)($_POST['id']??0);$code=trim((string)($_POST['product_code']??''));$name=PersianText::normalize($_POST['name']??'');if($id<1||$code===''||$name==='')throw new \RuntimeException('کد کالا و نام کالا الزامی است.');$type=PersianText::normalize($_POST['product_type']??'');$db->prepare('UPDATE products SET product_code=?,name=?,price=?,unit=?,product_type=?,allow_dine_in=?,allow_takeaway=?,status=?,updated_at=NOW() WHERE id=?')->execute([$code,$name,(float)($_POST['price']??0),PersianText::normalize($_POST['unit']??'')?:null,$type?:null,(int)!empty($_POST['allow_dine_in']),(int)!empty($_POST['allow_takeaway']),($_POST['status']??'active')==='active'?'active':'inactive',$id]);}
 public static function deleteProduct(PDO $db):void{$id=(int)($_POST['id']??0);if($id<1)throw new \RuntimeException('محصول نامعتبر است.');$db->prepare('DELETE FROM products WHERE id=?')->execute([$id]);}
 public static function bulkAssignProductType(PDO $db):int{$ids=array_values(array_filter(array_map('intval',(array)($_POST['product_ids']??[])),fn($id)=>$id>0));$type=PersianText::normalize($_POST['target_product_type']??'');if(!$ids||$type==='')throw new \RuntimeException('محصول و نوع مقصد را انتخاب کنید.');$s=$db->prepare('UPDATE products SET product_type=?,updated_at=NOW() WHERE id=?');$count=0;foreach($ids as $id){$s->execute([$type,$id]);$count+=(int)$s->rowCount();}return$count;}
 public static function bulkDeleteProducts(PDO $db):int{$ids=array_values(array_filter(array_map('intval',(array)($_POST['product_ids']??[])),fn($id)=>$id>0));if(!$ids)throw new \RuntimeException('حداقل یک محصول را انتخاب کنید.');$deleted=0;foreach($ids as $id){$s=$db->prepare('DELETE FROM products WHERE id=?');$s->execute([$id]);$deleted+=(int)$s->rowCount();}return$deleted;}
 private static function setSelectedProductType():void{$v=PersianText::normalize(trim((string)($_POST['selected_type']??'all')));$_SESSION['order_product_type_filter']=$v!==''?$v:'all';}
 public static function addItem(PDO $db):void{self::ensureCart();$id=(int)($_POST['product_id']??0);if($id<1)return;if(!self::productCanBeOrdered($db,$id))throw new \RuntimeException('این محصول به‌دلیل موجودی انبار در حال حاضر قابل سفارش نیست.');$_SESSION['order_cart'][$id]=($_SESSION['order_cart'][$id]??0)+1;}
 public static function decrementItem():void{self::ensureCart();$id=(int)($_POST['product_id']??0);if($id<1)return;$qty=(int)($_SESSION['order_cart'][$id]??0);if($qty>1)$_SESSION['order_cart'][$id]=$qty-1;else unset($_SESSION['order_cart'][$id]);}
 public static function clearCart():void{$_SESSION['order_cart']=[];}
 public static function cart(PDO $db):array{self::ensureCart();$items=[];$total=0;$ids=array_keys($_SESSION['order_cart']);if($ids){$in=implode(',',array_fill(0,count($ids),'?'));$s=$db->prepare("SELECT * FROM products WHERE id IN($in) AND status='active'");$s->execute($ids);foreach($s->fetchAll() as $p){$p['qty']=(int)($_SESSION['order_cart'][$p['id']]??0);$p['line_total']=$p['qty']*(float)$p['price'];$items[]=$p;$total+=$p['line_total'];}}return[$items,$total];}
 public static function finalize(PDO $db,array $customer):array{
  [$items,$subtotal]=self::cart($db);$discountPercent=self::discountPercent();$discountAmount=self::discountAmount($subtotal,$discountPercent);$total=max(0,$subtotal-$discountAmount);if(!$customer||!$items)throw new \RuntimeException('ابتدا مشتری و حداقل یک محصول را انتخاب کنید.');$method=$_POST['payment_method']??'cash';if(!in_array($method,['cash','card','online','mixed'],true))throw new \RuntimeException('شیوه پرداخت نامعتبر است.');
  self::syncDraft($db,$customer);$draftId=(int)($_SESSION['order_draft_id']??0);if($draftId<1)throw new \RuntimeException('پیش‌فاکتور قابل ثبت نیست.');$userId=(int)(Auth::user()['id']??0);$db->beginTransaction();
  try{$lock=$db->prepare("SELECT * FROM orders WHERE id=? AND created_by=? AND status='draft' FOR UPDATE");$lock->execute([$draftId,$userId]);if(!$lock->fetch())throw new \RuntimeException('پیش‌فاکتور پیدا نشد.');self::deductInventory($db,$draftId,$userId);$ticket=self::nextTicketNumber($db);$orderNo='R'.date('YmdHis').random_int(100,999);$invoiceNo='F'.date('YmdHis').random_int(100,999);$paymentNo='P'.date('YmdHis').random_int(100,999);
   $db->prepare("UPDATE orders SET order_no=?,customer_id=?,customer_phone=?,order_type=?,status='completed',subtotal_amount=?,discount_percent=?,discount_amount=?,total_amount=?,invoice_no=?,payment_method=?,paid_amount=?,finalized_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$orderNo,$customer['id'],$customer['phone'],self::orderType($db),$subtotal,$discountPercent,$discountAmount,$total,$invoiceNo,$method,$total,$draftId]);
   $db->prepare('INSERT INTO invoices(invoice_no,order_id,total_amount,discount_percent,discount_amount,ticket_date,ticket_no,created_at) VALUES(?,?,?,?,?,?,?,NOW())')->execute([$invoiceNo,$draftId,$total,$discountPercent,$discountAmount,date('Y-m-d'),$ticket]);
   $iid=(int)$db->lastInsertId();$db->prepare('INSERT INTO payments(payment_no,invoice_id,method,amount,created_at) VALUES(?,?,?,?,NOW())')->execute([$paymentNo,$iid,$method,$total]);AuditLogger::log($db,'ثبت و پرداخت سفارش','order',$draftId,null,['invoice_no'=>$invoiceNo,'ticket_no'=>$ticket,'subtotal'=>$subtotal,'discount_percent'=>$discountPercent,'discount_amount'=>$discountAmount,'total'=>$total,'payment_method'=>$method]);$db->commit();self::clearCart();unset($_SESSION['order_customer_phone'],$_SESSION['order_type'],$_SESSION['order_draft_id'],$_SESSION['order_discount_percent']);return['invoice_no'=>$invoiceNo,'ticket_no'=>$ticket,'total'=>$total];
  }catch(\Throwable $e){$db->rollBack();throw$e;}
 }
 private static function setOrderType(PDO $db):string{
  $v=(string)($_POST['order_type']??'سالن');$allowed=['سالن','بیرون‌بر'];if(!in_array($v,$allowed,true))$v=self::orderType($db);$_SESSION['order_type']=$v;return$v;
 }
 private static function applyDefaultProducts(PDO $db,string $orderType):void{
  self::ensureCart();$flag=$orderType==='بیرون‌بر'?'allow_takeaway':'allow_dine_in';$s=$db->query("SELECT p.id FROM products p WHERE p.status='active' AND p.{$flag}=1 AND NOT EXISTS (SELECT 1 FROM inventory_product_rules r INNER JOIN inventory_items i ON i.id=r.inventory_item_id WHERE r.product_id=p.id AND i.status='active' AND i.track_stock=1 AND i.current_quantity<r.quantity_per_order) ORDER BY p.id");foreach($s->fetchAll(PDO::FETCH_COLUMN) as $id){$id=(int)$id;if(!isset($_SESSION['order_cart'][$id]))$_SESSION['order_cart'][$id]=1;}
 }
 private static function discountPercent():float{$v=(float)($_SESSION['order_discount_percent']??0);return max(0,min(100,$v));}
 private static function setDiscount(string $value):void{$_SESSION['order_discount_percent']=max(0,min(100,(float)str_replace(',','.',$value)));}
 private static function discountAmount(float $subtotal,float $percent):float{return round($subtotal*$percent/100,2);}
 private static function restoreDraft(PDO $db):void{
  $userId=(int)(Auth::user()['id']??0);if($userId<1)return;$draftId=(int)($_SESSION['order_draft_id']??0);if($draftId<1)return;
  $s=$db->prepare("SELECT * FROM orders WHERE id=? AND created_by=? AND status='draft' LIMIT 1");$s->execute([$draftId,$userId]);$draft=$s->fetch();if($draft)self::loadDraft($db,$draft);else self::forgetActiveDraft();
 }
 private static function findDraft(PDO $db,int $draftId):?array{
  $userId=(int)(Auth::user()['id']??0);if($userId<1)return null;$s=$db->prepare("SELECT * FROM orders WHERE id=? AND created_by=? AND status='draft' LIMIT 1");$s->execute([$draftId,$userId]);return$s->fetch()?:null;
 }
 private static function deleteDraft(PDO $db,int $draftId):void{
  $userId=(int)(Auth::user()['id']??0);if($userId<1||$draftId<1)throw new \RuntimeException('فاکتور نامعتبر است.');
  $s=$db->prepare("SELECT id FROM orders WHERE id=? AND created_by=? AND status='draft' LIMIT 1");$s->execute([$draftId,$userId]);if(!$s->fetch())throw new \RuntimeException('فاکتور در دست اقدام پیدا نشد.');
  $db->beginTransaction();try{$db->prepare('DELETE FROM order_items WHERE order_id=?')->execute([$draftId]);$db->prepare("DELETE FROM orders WHERE id=? AND created_by=? AND status='draft'")->execute([$draftId,$userId]);$db->commit();if((int)($_SESSION['order_draft_id']??0)===$draftId)self::forgetActiveDraft();}catch(\Throwable $e){$db->rollBack();throw$e;}
 }
 private static function pendingDrafts(PDO $db):array{
  $userId=(int)(Auth::user()['id']??0);if($userId<1)return[];$s=$db->prepare("SELECT o.id,o.order_no,o.order_type,o.customer_phone,o.subtotal_amount,o.discount_percent,o.discount_amount,o.total_amount,o.updated_at,o.created_at,COALESCE(c.name,o.customer_phone,'بدون مشتری') customer_name,(SELECT COUNT(*) FROM order_items oi WHERE oi.order_id=o.id) item_count FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.created_by=? AND o.status='draft' ORDER BY COALESCE(o.updated_at,o.created_at) DESC,o.id DESC");$s->execute([$userId]);return$s->fetchAll();
 }
 private static function forgetActiveDraft():void{unset($_SESSION['order_draft_id'],$_SESSION['order_customer_phone'],$_SESSION['order_discount_percent'],$_SESSION['order_type']);$_SESSION['order_cart']=[];}
 private static function loadDraft(PDO $db,array $draft):void{
  $_SESSION['order_draft_id']=(int)$draft['id'];$_SESSION['order_type']=$draft['order_type'];$_SESSION['order_discount_percent']=(float)$draft['discount_percent'];if(!empty($draft['customer_phone']))$_SESSION['order_customer_phone']=$draft['customer_phone'];$_SESSION['order_cart']=[];$s=$db->prepare('SELECT product_id,quantity FROM order_items WHERE order_id=?');$s->execute([(int)$draft['id']]);foreach($s->fetchAll() as $it)$_SESSION['order_cart'][(int)$it['product_id']]=max(1,(int)$it['quantity']);
 }
 private static function syncDraft(PDO $db,?array $customer):void{
  [$items,$subtotal]=self::cart($db);$percent=self::discountPercent();$discount=self::discountAmount($subtotal,$percent);$total=max(0,$subtotal-$discount);$userId=(int)(Auth::user()['id']??0);if($userId<1)return;$draftId=(int)($_SESSION['order_draft_id']??0);
  if($draftId>0){$s=$db->prepare("SELECT id FROM orders WHERE id=? AND created_by=? AND status='draft' LIMIT 1");$s->execute([$draftId,$userId]);if(!$s->fetch())$draftId=0;}
  if($draftId<1){if(!$customer&&!$items)return;$s=$db->prepare("INSERT INTO orders(order_no,customer_id,customer_phone,order_type,status,subtotal_amount,discount_percent,discount_amount,total_amount,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,NOW(),?)");$s->execute(['D'.date('YmdHis').random_int(100,999),$customer['id']??null,$customer['phone']??null,self::orderType($db),'draft',$subtotal,$percent,$discount,$total,$userId]);$draftId=(int)$db->lastInsertId();$_SESSION['order_draft_id']=$draftId;}
  else{$db->prepare('UPDATE orders SET customer_id=?,customer_phone=?,order_type=?,subtotal_amount=?,discount_percent=?,discount_amount=?,total_amount=?,updated_at=NOW() WHERE id=?')->execute([$customer['id']??null,$customer['phone']??null,self::orderType($db),$subtotal,$percent,$discount,$total,$draftId]);$db->prepare('DELETE FROM order_items WHERE order_id=?')->execute([$draftId]);}
  if($draftId>0&&$items){$ins=$db->prepare('INSERT INTO order_items(order_id,product_id,quantity,unit_price,line_total,created_at) VALUES(?,?,?,?,?,NOW())');foreach($items as $p){$q=(int)$p['qty'];$ins->execute([$draftId,$p['id'],$q,$p['price'],$q*$p['price']]);}}
 }
 private static function productCanBeOrdered(PDO $db,int $productId):bool{
  $s=$db->prepare("SELECT 1 FROM products p WHERE p.id=? AND p.status='active' AND NOT EXISTS (SELECT 1 FROM inventory_product_rules r INNER JOIN inventory_items i ON i.id=r.inventory_item_id WHERE r.product_id=p.id AND i.status='active' AND i.track_stock=1 AND i.current_quantity<r.quantity_per_order) LIMIT 1");
  $s->execute([$productId]);return(bool)$s->fetchColumn();
 }
 private static function deductInventory(PDO $db,int $orderId,int $userId):void{
  $s=$db->prepare('SELECT oi.product_id,oi.quantity,p.name product_name FROM order_items oi INNER JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? ORDER BY oi.id');$s->execute([$orderId]);
  $rules=$db->prepare("SELECT r.inventory_item_id,r.quantity_per_order,i.name item_name,i.unit,i.track_stock FROM inventory_product_rules r INNER JOIN inventory_items i ON i.id=r.inventory_item_id WHERE r.product_id=? AND i.status='active' ORDER BY r.id");
  foreach($s->fetchAll() as $orderItem){
   $rules->execute([(int)$orderItem['product_id']]);
   foreach($rules->fetchAll() as $rule){
    if((int)$rule['track_stock']!==1)continue;
    $required=(float)$orderItem['quantity']*(float)$rule['quantity_per_order'];if($required<=0)continue;
    $lock=$db->prepare('SELECT current_quantity FROM inventory_items WHERE id=? FOR UPDATE');$lock->execute([(int)$rule['inventory_item_id']]);$available=(float)$lock->fetchColumn();
    if($available+0.000001<$required)throw new \RuntimeException('موجودی «'.(string)$rule['item_name'].'» برای «'.(string)$orderItem['product_name'].'» کافی نیست. موجودی فعلی: '.rtrim(rtrim(number_format($available,3,'.',''),'0'),'.').' '.(string)$rule['unit'].'؛ نیاز: '.rtrim(rtrim(number_format($required,3,'.',''),'0'),'.').' '.(string)$rule['unit']);
    $db->prepare('UPDATE inventory_items SET current_quantity=current_quantity-?,updated_at=NOW() WHERE id=?')->execute([$required,(int)$rule['inventory_item_id']]);
    $db->prepare("INSERT INTO inventory_movements(inventory_item_id,product_id,order_id,quantity_change,movement_type,note,created_by,created_at) VALUES(?,?,?,?, 'order',?,?,NOW())")->execute([(int)$rule['inventory_item_id'],(int)$orderItem['product_id'],$orderId,-$required,'کسر خودکار بابت سفارش', $userId?:null]);
   }
  }
 }
 private static function nextTicketNumber(PDO $db):int{$today=date('Y-m-d');$db->prepare('INSERT INTO daily_ticket_sequences(ticket_date,last_no) VALUES(?,0) ON DUPLICATE KEY UPDATE last_no=last_no')->execute([$today]);$s=$db->prepare('SELECT last_no FROM daily_ticket_sequences WHERE ticket_date=? FOR UPDATE');$s->execute([$today]);$next=((int)$s->fetchColumn())+1;$db->prepare('UPDATE daily_ticket_sequences SET last_no=? WHERE ticket_date=?')->execute([$next,$today]);return$next;}
 private static function orderType(PDO $db):string{
  $v=(string)($_SESSION['order_type']??'');if(in_array($v,['سالن','بیرون‌بر'],true))return$v;
  try{$s=$db->prepare("SELECT setting_value FROM settings WHERE scope='sales' AND setting_key='default_order_type' LIMIT 1");$s->execute();$x=json_decode((string)$s->fetchColumn(),true);if(in_array($x,['سالن','بیرون‌بر'],true))return$x;}catch(\Throwable $e){}
  return 'سالن';
 }
 private static function ensureCart():void{if(!isset($_SESSION['order_cart'])||!is_array($_SESSION['order_cart']))$_SESSION['order_cart']=[];}
 private static function normalizeDigits(string $v):string{return PersianDate::latinDigits(trim($v));}
 private static function friendly(\Throwable $e):string{if(str_contains($e->getMessage(),'Duplicate entry'))return'این اطلاعات قبلاً ثبت شده است.';return$e->getMessage();}
}