<?php
declare(strict_types=1);
namespace App\Http\Controllers;
use App\Support\AuditLogger;use App\Support\PersianText;use PDO;
final class SettingsController{
 public static function index(PDO $db):array{$tab=(string)($_GET['tab']??$_POST['tab']??'general');$message=null;$error=null;try{if($_SERVER['REQUEST_METHOD']==='POST'){switch($_POST['action']??''){case'create_category':self::createCategory($db,$message);break;case'update_category':self::updateCategory($db,$message);break;case'delete_category':self::deleteCategory($db,$message);break;case'save_print':self::savePrint($db,$message);break;case'save_sales':self::saveGeneric($db,'sales',['default_order_type','allow_paid_edit']);break;case'save_restaurant':self::saveRestaurant($db,$message);break;case'create_printer':self::createPrinter($db,$message);break;case'delete_printer':self::deletePrinter($db,$message);break;}}}catch(\Throwable $e){$error=self::friendly($e);} $rows=$db->query('SELECT c.*,COUNT(p.id) product_count FROM product_categories c LEFT JOIN products p ON p.product_type=c.name GROUP BY c.id ORDER BY c.sort_order,c.name')->fetchAll();$printers=$db->query('SELECT * FROM printers ORDER BY is_default DESC,name')->fetchAll();$print=PrintController::settings($db);$sales=self::getScope($db,'sales');$restaurant=self::restaurant($db);return compact('tab','rows','printers','print','sales','restaurant','message','error');}
 private static function createCategory(PDO $db,?string &$message):void{$name=PersianText::normalize($_POST['name']??'');$color=trim((string)($_POST['color']??'#2563eb'));if($name===''||!preg_match('/^#[0-9A-Fa-f]{6}$/',$color))throw new \RuntimeException('اطلاعات نوع محصول نامعتبر است.');$db->prepare('INSERT INTO product_categories(name,color,icon,sort_order,status,created_at) VALUES(?,?,?,?,?,NOW())')->execute([$name,$color,trim((string)($_POST['icon']??'🍽️'))?:'🍽️',(int)($_POST['sort_order']??0),'active']);AuditLogger::log($db,'ایجاد نوع محصول','product_type',null,null,['name'=>$name]);$message='نوع محصول ثبت شد.';}
 private static function updateCategory(PDO $db,?string &$message):void{$id=(int)($_POST['id']??0);$name=PersianText::normalize($_POST['name']??'');$color=trim((string)($_POST['color']??'#2563eb'));$s=$db->prepare('SELECT * FROM product_categories WHERE id=?');$s->execute([$id]);$old=$s->fetch();if(!$old||$name===''||!preg_match('/^#[0-9A-Fa-f]{6}$/',$color))throw new \RuntimeException('اطلاعات نوع محصول نامعتبر است.');$db->beginTransaction();try{$db->prepare('UPDATE products SET product_type=?,updated_at=NOW() WHERE product_type=?')->execute([$name,$old['name']]);$db->prepare('UPDATE product_categories SET name=?,color=?,icon=?,sort_order=?,updated_at=NOW() WHERE id=?')->execute([$name,$color,trim((string)($_POST['icon']??'🍽️'))?:'🍽️',(int)($_POST['sort_order']??0),$id]);$db->commit();AuditLogger::log($db,'ویرایش نوع محصول','product_type',$id,$old,['name'=>$name,'color'=>$color]);$message='نوع محصول ویرایش شد.';}catch(\Throwable $e){$db->rollBack();throw$e;}}
 private static function deleteCategory(PDO $db,?string &$message):void{$id=(int)($_POST['id']??0);$s=$db->prepare('SELECT * FROM product_categories WHERE id=?');$s->execute([$id]);$old=$s->fetch();if(!$old)throw new \RuntimeException('نوع پیدا نشد.');$db->beginTransaction();try{$db->prepare('UPDATE products SET product_type=NULL,updated_at=NOW() WHERE product_type=?')->execute([$old['name']]);$db->prepare('DELETE FROM product_categories WHERE id=?')->execute([$id]);$db->commit();AuditLogger::log($db,'حذف نوع محصول','product_type',$id,$old);$message='نوع محصول حذف شد.';}catch(\Throwable $e){$db->rollBack();throw$e;}}
 private static function savePrint(PDO $db,?string &$message):void{$keys=['paper_width','show_logo','show_address','show_phone','show_customer','show_invoice_no','show_date','show_payment','show_footer' ,'footer_text','feed','cut','kitchen_title','kitchen_show_restaurant','kitchen_show_order_type','kitchen_show_customer','kitchen_show_invoice_no','kitchen_show_date','kitchen_show_product_type','kitchen_footer'];foreach($keys as $k){$v=(string)($_POST[$k]??($k==='footer_text'?'':(($k==='paper_width')?'80mm':'0')));if(str_starts_with($k,'show_'))$v=isset($_POST[$k])?'1':'0';$s=$db->prepare("INSERT INTO settings(scope,setting_key,setting_value) VALUES('print',?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");$s->execute([$k,json_encode($v,JSON_UNESCAPED_UNICODE)]);}AuditLogger::log($db,'تغییر تنظیمات چاپ','settings');$message='تنظیمات چاپ ذخیره شد.';}
 private static function saveRestaurant(PDO $db,?string &$message):void{
  $name=trim((string)($_POST['name']??''));if($name==='')throw new \RuntimeException('نام رستوران الزامی است.');
  $old=self::restaurant($db);$logo=$old['logo_path']??null;
  if(isset($_FILES['logo'])&&($_FILES['logo']['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_OK){
   $tmp=$_FILES['logo']['tmp_name'];$mime=(string)(mime_content_type($tmp)?:'');$allowed=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp','image/svg+xml'=>'svg'];
   if(!isset($allowed[$mime]))throw new \RuntimeException('فرمت لوگو باید PNG، JPG، WEBP یا SVG باشد.');
   if((int)$_FILES['logo']['size']>2*1024*1024)throw new \RuntimeException('حجم لوگو نباید بیشتر از ۲ مگابایت باشد.');
   $dir=dirname(__DIR__,3).'/public/uploads/restaurant';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new \RuntimeException('امکان ایجاد پوشه لوگو وجود ندارد.');
   $file='logo_'.bin2hex(random_bytes(8)).'.'.$allowed[$mime];if(!move_uploaded_file($tmp,$dir.'/'.$file))throw new \RuntimeException('ذخیره لوگو انجام نشد.');$logo='/uploads/restaurant/'.$file;
  }
  $sql='INSERT INTO restaurant_profile(id,name,address,phone,mobile,email,website,logo_path,description,updated_at) VALUES(1,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),address=VALUES(address),phone=VALUES(phone),mobile=VALUES(mobile),email=VALUES(email),website=VALUES(website),logo_path=VALUES(logo_path),description=VALUES(description),updated_at=NOW()';
  $db->prepare($sql)->execute([$name,trim((string)($_POST['address']??''))?:null,trim((string)($_POST['phone']??''))?:null,trim((string)($_POST['mobile']??''))?:null,trim((string)($_POST['email']??''))?:null,trim((string)($_POST['website']??''))?:null,$logo,trim((string)($_POST['description']??''))?:null]);
  AuditLogger::log($db,'ویرایش مشخصات رستوران','restaurant_profile',1,$old,self::restaurant($db));$message='مشخصات رستوران ذخیره شد.';
 }
 private static function restaurant(PDO $db):array{$s=$db->query('SELECT * FROM restaurant_profile WHERE id=1');return$s->fetch()?:['id'=>1,'name'=>'رستوران','address'=>'','phone'=>'','mobile'=>'','email'=>'','website'=>'','logo_path'=>'','description'=>''];}
 private static function saveGeneric(PDO $db,string $scope,array $keys):void{foreach($keys as $k){$v=(string)($_POST[$k]??'');$db->prepare("INSERT INTO settings(scope,setting_key,setting_value) VALUES(?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")->execute([$scope,$k,json_encode($v,JSON_UNESCAPED_UNICODE)]);}}
 private static function createPrinter(PDO $db,?string &$message):void{$name=trim((string)($_POST['name']??''));if($name==='')throw new \RuntimeException('نام چاپگر الزامی است.');$db->beginTransaction();try{if(!empty($_POST['is_default']))$db->exec("UPDATE printers SET is_default=0");$db->prepare('INSERT INTO printers(name,location,printer_type,connection_type,address,paper_width,is_default,status,created_at) VALUES(?,?,?,?,?,?,?,"active",NOW())')->execute([$name,trim((string)($_POST['location']??''))?:null,$_POST['printer_type']??'receipt',$_POST['connection_type']??'browser',trim((string)($_POST['address']??''))?:null,$_POST['paper_width']??'80mm',!empty($_POST['is_default'])?1:0]);$id=(int)$db->lastInsertId();$db->commit();AuditLogger::log($db,'ایجاد چاپگر','printer',$id,null,['name'=>$name]);$message='چاپگر ثبت شد.';}catch(\Throwable $e){$db->rollBack();throw$e;}}
 private static function deletePrinter(PDO $db,?string &$message):void{$id=(int)($_POST['id']??0);$s=$db->prepare('DELETE FROM printers WHERE id=?');$s->execute([$id]);AuditLogger::log($db,'حذف چاپگر','printer',$id);$message='چاپگر حذف شد.';}
 private static function getScope(PDO $db,string $scope):array{$s=$db->prepare('SELECT setting_key,setting_value FROM settings WHERE scope=?');$s->execute([$scope]);$r=[];foreach($s->fetchAll() as $x){$v=json_decode((string)$x['setting_value'],true);$r[$x['setting_key']]=(string)$v;}return$r;}
 private static function friendly(\Throwable $e):string{if(str_contains($e->getMessage(),'Duplicate entry'))return'این مقدار قبلاً ثبت شده است.';return$e->getMessage();}
}