<section class="page-head"><div><div class="eyebrow">CRM</div><h1>مشتریان</h1><p>ثبت، جستجو، ویرایش، حذف و ورود گروهی مشتریان.</p></div><div class="head-actions"><a class="btn btn-primary" href="/?page=customers&new=1">＋ مشتری جدید</a></div></section>
<?php if(!empty($message)): ?><div class="alert success"><?=htmlspecialchars($message)?></div><?php endif; ?><?php if(!empty($error)): ?><div class="alert"><?=htmlspecialchars($error)?></div><?php endif; ?>
<?php if(isset($_GET['new']) || $edit): $r=$edit?:[]; ?>
<form method="post" class="card form-card"><input type="hidden" name="action" value="<?=$edit?'update_customer':'create_customer' ?>"><?php if($edit): ?><input type="hidden" name="id" value="<?=$r['id']?>"><?php endif; ?><div class="form-grid">
<label>کد اشتراک<input name="subscription_code" value="<?=htmlspecialchars($r['subscription_code']??'')?>"></label><label>شماره تلفن *<input name="phone" required inputmode="tel" value="<?=htmlspecialchars($r['phone']??'')?>"></label>
<label>نام *<input name="first_name" required value="<?=htmlspecialchars($r['first_name']??'')?>"></label><label>نام خانوادگی *<input name="last_name" required value="<?=htmlspecialchars($r['last_name']??'')?>"></label>
<label>تلفن همراه<input name="mobile" inputmode="tel" value="<?=htmlspecialchars($r['mobile']??'')?>"></label><label>تاریخ عضویت (شمسی)<input name="membership_date" placeholder="1405/07/13" value="<?=htmlspecialchars(App\Support\PersianDate::format($r['membership_date']??null,false))?>"></label>
<label>تاریخ تولد (شمسی)<input name="birth_date" placeholder="1375/01/01" value="<?=htmlspecialchars(App\Support\PersianDate::format($r['birth_date']??null,false))?>"></label><label>آدرس<input name="address" value="<?=htmlspecialchars($r['address']??'')?>"></label>
<div class="form-actions"><button class="btn btn-primary"><?=$edit?'ذخیره تغییرات':'ثبت مشتری'?></button><a class="btn" href="/?page=customers">انصراف</a></div></div></form>
<?php endif; ?>
<section class="card section-card"><div class="toolbar"><input class="search-input" data-global-search-local placeholder="جستجو نام یا تلفن..."><form method="post" enctype="multipart/form-data" class="csv-form"><input type="hidden" name="action" value="import_customers_csv"><input type="file" name="csv" accept=".csv,text/csv" required><button class="btn">ورود CSV</button></form></div>
<div class="table-wrap"><table><thead><tr><th>کد اشتراک</th><th>نام</th><th>تلفن</th><th>موبایل</th><th>عضویت</th><th>تولد</th><th>عملیات</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="7"><div class="empty"><strong>مشتری ثبت نشده است</strong><span>مشتری جدید اضافه کنید یا CSV وارد کنید.</span></div></td></tr>
<?php else: foreach($rows as $r): ?><tr data-local-search="<?=htmlspecialchars($r['name'].' '.$r['phone'].' '.($r['subscription_code']??''))?>"><td><?=htmlspecialchars($r['subscription_code']??'—')?></td><td><strong><?=htmlspecialchars($r['name'])?></strong></td><td><?=htmlspecialchars($r['phone'])?></td><td><?=htmlspecialchars($r['mobile']??'—')?></td><td><?=htmlspecialchars(App\Support\PersianDate::format($r['membership_date'],false))?></td><td><?=htmlspecialchars(App\Support\PersianDate::format($r['birth_date'],false))?></td><td class="row-actions"><a class="btn btn-sm" href="/?page=customers&edit=<?=$r['id']?>">ویرایش</a><form method="post" onsubmit="return confirm('مشتری حذف شود؟')"><input type="hidden" name="action" value="delete_customer"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-danger">حذف</button></form></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
