<section class="page-head"><div><div class="eyebrow">POS / فروش</div><h1>ثبت سفارش و صدور فاکتور</h1><p>مشتری را با نام یا شماره تلفن پیدا کنید؛ اگر وجود نداشت، همان‌جا ثبتش کنید.</p></div></section>
<?php if(!empty($message)): ?><div class="alert success"><?=htmlspecialchars($message)?></div><?php endif; ?><?php if(!empty($error)): ?><div class="alert"><?=htmlspecialchars($error)?></div><?php endif; ?><?php if(!empty($_GET['success'])): ?><div class="success-box"><strong>فاکتور با موفقیت ثبت شد</strong><span>شماره فاکتور: <?=htmlspecialchars($_GET['success'])?></span></div><?php endif; ?>
<div class="pos-grid"><section class="card pos-main">
<div class="card-head"><div><h2>۱. انتخاب مشتری</h2><small>جستجو با نام، نام خانوادگی یا شماره تلفن</small></div></div>
<form class="customer-search" method="get"><input type="hidden" name="page" value="orders"><input class="field" name="phone" value="<?=htmlspecialchars($phone??'')?>" inputmode="search" placeholder="نام مشتری یا 09121234567" required><button class="btn btn-primary">جستجو</button></form>
<?php if($customer): ?><div class="customer-result"><div class="customer-avatar">♙</div><div><strong><?=htmlspecialchars($customer['name'])?></strong><small>تلفن: <?=htmlspecialchars($customer['phone'])?> · موبایل: <?=htmlspecialchars($customer['mobile']??'—')?> · اشتراک: <?=htmlspecialchars($customer['subscription_code']??'—')?></small></div><span class="badge success">انتخاب شد</span></div>
<?php elseif(($phone??'')!==''): ?><form method="post" class="new-order-customer"><input type="hidden" name="action" value="add_customer_order"><div class="new-customer-head"><strong>مشتری پیدا نشد</strong><small>اطلاعات را همین‌جا وارد کنید تا بلافاصله برای فاکتور انتخاب شود.</small></div><div class="order-customer-grid">
<label>نام *<input name="first_name" required></label><label>نام خانوادگی *<input name="last_name" required></label><label>شماره تلفن *<input name="phone" required inputmode="tel" value="<?=htmlspecialchars($phone??'')?>"></label><label>موبایل<input name="mobile" inputmode="tel"></label><label>کد اشتراک<input name="subscription_code"></label><label>تاریخ عضویت<input name="membership_date" placeholder="1405/07/13"></label><label>تاریخ تولد<input name="birth_date" placeholder="1375/01/01"></label><label>آدرس<input name="address"></label></div><button class="btn btn-primary">ثبت و انتخاب مشتری</button></form><?php endif; ?>
<div class="card-head product-head"><div><h2>۲. انتخاب محصولات</h2><small>کلیک روی محصول، تعداد آن را یک واحد افزایش می‌دهد.</small></div><input class="search-input" data-product-search placeholder="جستجوی محصول..."></div>
<div class="product-grid" data-products><?php foreach($products as $p): $numeric=preg_replace('/\D+/','',(string)$p['product_code']); $bucket=$numeric!==''?(int)floor(((int)$numeric)/100):(int)floor(((int)$p['id'])/100); $bucket=$bucket%8; ?>
<form class="product-card product-color-<?=$bucket?>" method="post" data-product><input type="hidden" name="action" value="add_item"><input type="hidden" name="product_id" value="<?=$p['id']?>"><button type="submit"><span class="product-type"><?=htmlspecialchars($p['product_type']??'محصول')?></span><strong><?=htmlspecialchars($p['name'])?></strong><small><?=htmlspecialchars($p['product_code'])?></small><b><?=number_format((float)$p['price'])?> <i>ریال</i></b></button></form><?php endforeach; ?></div>
</section>
<aside class="card invoice-card"><div class="invoice-top"><div><span>پیش‌فاکتور</span><strong>جدید</strong></div><div class="invoice-date"><?=htmlspecialchars(App\Support\PersianDate::today())?></div></div>
<div class="invoice-customer"><?php if($customer): ?><span>مشخصات مشتری</span><strong><?=htmlspecialchars($customer['name'])?></strong><small>تلفن: <?=htmlspecialchars($customer['phone'])?></small><small>موبایل: <?=htmlspecialchars($customer['mobile']??'—')?> · اشتراک: <?=htmlspecialchars($customer['subscription_code']??'—')?></small><small>آدرس: <?=htmlspecialchars($customer['address']??'—')?></small><?php else: ?><span class="muted">مشتری انتخاب نشده</span><?php endif; ?></div>
<div class="invoice-items"><?php if(!$items): ?><div class="empty compact"><strong>فاکتور خالی است</strong><span>از لیست محصولات انتخاب کنید.</span></div><?php else: foreach($items as $it): ?><div class="invoice-item"><div><strong><?=htmlspecialchars($it['name'])?></strong><small><?=number_format((float)$it['price'])?> × <?=$it['qty']?></small></div><b><?=number_format((float)$it['line_total'])?></b><form method="post"><input type="hidden" name="action" value="remove_item"><input type="hidden" name="product_id" value="<?=$it['id']?>"><button aria-label="حذف">×</button></form></div><?php endforeach; endif; ?></div>
<div class="invoice-total"><span>مبلغ نهایی</span><strong><?=number_format((float)$total)?> <small>ریال</small></strong></div>
<form method="post" class="finalize-form"><input type="hidden" name="action" value="finalize"><input type="hidden" name="customer_phone" value="<?=htmlspecialchars($customer['phone']??'')?>"><label>شیوه پرداخت<select name="payment_method"><option value="cash">نقدی</option><option value="card">کارتخوان</option><option value="online">آنلاین</option><option value="mixed">ترکیبی</option></select></label><button class="btn btn-primary finalize-btn" <?=(!$customer||!$items)?'disabled':''?>>ثبت نهایی و صدور فاکتور</button></form>
<form method="post"><input type="hidden" name="action" value="clear_cart"><button class="btn clear-btn" <?=!$items?'disabled':''?>>خالی کردن فاکتور</button></form></aside></div>
<script>
document.querySelector('[data-product-search]')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('[data-product]').forEach(x=>x.hidden=q&&!x.textContent.toLowerCase().includes(q));});
</script>