<section class="page-head"><div><div class="eyebrow">MENU</div><h1>منو و محصولات</h1><p>محصولات را مدیریت کنید؛ «نوع محصول» همان دسته‌بندی است و رنگ آن از تنظیمات نوع تعیین می‌شود.</p></div><div class="head-actions"><a class="btn btn-primary" href="/?page=products&new=1">＋ محصول جدید</a></div></section>
<?php if(!empty($message)): ?><div class="alert success"><?=htmlspecialchars($message)?></div><?php endif; ?><?php if(!empty($error)): ?><div class="alert"><?=htmlspecialchars($error)?></div><?php endif; ?>
<?php if(isset($_GET['new']) || $edit): $r=$edit?:[]; ?>
<form method="post" class="card form-card"><input type="hidden" name="action" value="<?=$edit?'update_product':'create_product'?>"><?php if($edit): ?><input type="hidden" name="id" value="<?=$r['id']?>"><?php endif; ?><div class="form-grid">
<label>کد کالا *<input name="product_code" required value="<?=htmlspecialchars($r['product_code']??'')?>"></label><label>نام کالا *<input name="name" required value="<?=htmlspecialchars($r['name']??'')?>"></label>
<label>قیمت واحد *<input name="price" type="number" min="0" required value="<?=htmlspecialchars((string)($r['price']??''))?>"></label><label>واحد<input name="unit" value="<?=htmlspecialchars($r['unit']??'')?>"></label>
<label>نوع / دسته‌بندی<select name="product_type"><option value="">بدون نوع</option><?php foreach($categories as $cat): ?><option value="<?=htmlspecialchars($cat['name'])?>" <?=((string)($r['product_type']??'')===(string)$cat['name'])?'selected':''?>><?=htmlspecialchars($cat['name'])?></option><?php endforeach; ?></select></label>
<label class="check-setting"><input type="checkbox" name="allow_dine_in" value="1" <?=((int)($r['allow_dine_in']??1)===1)?'checked':''?> سالن</label><label class="check-setting"><input type="checkbox" name="allow_takeaway" value="1" <?=((int)($r['allow_takeaway']??1)===1)?'checked':''?> بیرون‌بر</label><label>وضعیت<select name="status"><option value="active" <?=($r['status']??'active')==='active'?'selected':''?>>فعال</option><option value="inactive" <?=($r['status']??'')==='inactive'?'selected':''?>>غیرفعال</option></select></label>
<div class="form-actions"><button class="btn btn-primary"><?=$edit?'ذخیره تغییرات':'ثبت محصول'?></button><a class="btn" href="/?page=products">انصراف</a></div></div></form>
<?php endif; ?>
<form method="post" id="bulk-products-form"><input type="hidden" name="action" value="bulk_delete_products"></form>
<section class="card section-card"><div class="toolbar"><div class="filters"><input class="search-input" data-global-search-local placeholder="جستجو نام یا کد کالا..."><select name="target_product_type" form="bulk-products-form" required><option value="">انتقال به نوع...</option><?php foreach($categories as $cat): ?><option value="<?=htmlspecialchars($cat['name'])?>"><?=htmlspecialchars($cat['name'])?></option><?php endforeach; ?></select><button class="btn btn-primary" type="submit" name="action" value="bulk_assign_product_type" form="bulk-products-form">انتقال به نوع</button><button class="btn btn-danger" type="submit" name="action" value="bulk_delete_products" form="bulk-products-form" onclick="return confirm('محصولات انتخاب‌شده حذف شوند؟')">حذف انتخاب‌شده‌ها</button></div><span class="muted">چند محصول را انتخاب کنید و در صورت نیاز نوع مشترک آن‌ها را تغییر دهید.</span></div>
<div class="table-wrap"><table><thead><tr><th>انتخاب</th><th>کد کالا</th><th>نام کالا</th><th>نوع / دسته‌بندی</th><th>مجاز در سفارش</th><th>قیمت</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="8"><div class="empty"><strong>محصولی ثبت نشده است</strong><span>محصول جدید اضافه کنید یا CSV وارد کنید.</span></div></td></tr>
<?php else: foreach($rows as $r): ?><tr data-local-search="<?=htmlspecialchars($r['name'].' '.$r['product_code'].' '.($r['category_name']??''))?>"><td><input type="checkbox" name="product_ids[]" value="<?=$r['id']?>" form="bulk-products-form"></td><td><strong><?=htmlspecialchars($r['product_code'])?></strong></td><td><?=htmlspecialchars($r['name'])?></td><td><span class="category-badge" style="--cat:<?=htmlspecialchars($r['category_color']??'#64748b')?>"><?=htmlspecialchars($r['product_type']??'بدون نوع')?></span></td><td><span class="badge <?=((int)($r['allow_dine_in']??1)===1?'success':'danger')?>">سالن <?=((int)($r['allow_dine_in']??1)===1?'✓':'×')?></span> <span class="badge <?=((int)($r['allow_takeaway']??1)===1?'success':'danger')?>">بیرون‌بر <?=((int)($r['allow_takeaway']??1)===1?'✓':'×')?></span></td><td><?=number_format((float)$r['price'])?> ریال</td><td><span class="badge <?=($r['status']==='active'?'success':'danger')?>"><?=($r['status']==='active'?'فعال':'غیرفعال')?></span></td><td class="row-actions"><a class="btn btn-sm" href="/?page=products&edit=<?=$r['id']?>">ویرایش</a><form method="post" onsubmit="return confirm('محصول حذف شود؟')"><input type="hidden" name="action" value="delete_product"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-danger">حذف</button></form></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
<section class="card section-card csv-section"><div class="toolbar"><strong>ورود محصولات از CSV</strong><form method="post" enctype="multipart/form-data" class="csv-form"><input type="hidden" name="action" value="import_products_csv"><input type="file" name="csv" accept=".csv,text/csv" required><button class="btn">ورود CSV</button></form></div></section>